[package]
name = "lightning-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-model = { path = "../lightning-model" }
copypasta = "0.10"
glutin = "0.31"
raw-window-handle = "0.5.0"
winit = { version = "0.29", features = ["rwh_05"] }
imgui = "0.12"
imgui-glow-renderer = "0.12"
imgui-winit-support =  "0.12"
glutin-winit = "0.4"
glow = "0.13"
dirs = "4"
serde = "1.0"
serde_json = "1.0"
rustc-hash = "1.1"
lazy_static = "1.4"
glam = "0.27.0"
ddsfile = "0.5"
quadtree-f32 = "0.4.0"
