[package]
name = "lightning-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-model = { path = "../lightning-model" }
clipboard = "0.5"
glutin = { version = "0.29", default-features = false, features = ["x11"] }
imgui = "0.10"
glow = "0.10"
imgui-glow-renderer = "0.10"
winit = { version = "0.27", default-features = false, features = ["x11"] }
imgui-winit-support =  "0.10"
dirs = "4"
serde = "1.0"
serde_json = "1.0"
rustc-hash = "1.1"
lazy_static = "1.4"
glam = "0.22.0"
ddsfile = "0.5.1"
