[package]
name = "lightning-app"
version = "0.1.0"
edition = "2021"

[dependencies]
lightning-model = { path = "../lightning-model", default-features = false }
copypasta = "0.10"
glutin = "0.31"
raw-window-handle = "0.5.0"
imgui = "0.12"
imgui-glow-renderer = "0.12"
imgui-winit-support =  "0.12"
glutin-winit = "0.4"
glow = "0.13"
dirs = "4"
serde = "1.0"
serde_json = "1.0"
rustc-hash = "1.1"
lazy_static = "1.4"
glam = "0.27"
image = { version = "0.25", default-features = false, features = ["rayon", "jpeg", "png"] }
quadtree-f32 = "0.4"

[features]
default = ["import"]
import = ["lightning-model/import"]